name: CI 

on:
  push:
    branches:
      - main
    tags: '*'

  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        build-type: ["Debug", "Release", "MinSizeRel"]
    steps:
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Check Ninja (debugging)
        if: matrix.os == 'windows-latest'
        run: ninja --version
      - name: Build
        run: make all BUILD_TYPE=${{ matrix.build-type }}
  build-programmer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build SCuM nRF programmer
        run:
          make scum-programmer-in-docker
