name: CI 

on:
  push:
    branches:
      - main
    tags: '*'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: carlosperate/arm-none-eabi-gcc-action@v1
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        run: make -C samples/hello_world
